KerasJson: ../example-models/keras/KERAS_dense_16x100x100x100x100x100x5.json
KerasH5:   ../example-models/keras/KERAS_dense_16x100x100x100x100x100x5_weights.h5
OutputDir: quartus_prj/KERAS_dense_16x100x100x100x100x100x5-python3--c5-io_parallel-rf100-_16_6_-Latency
ProjectName: myproject
FPGApart: Arria10
ClockPeriod: 5
Backend: Quartus

IOType: io_parallel
HLSConfig:
  Model:
    ReuseFactor: 100
    Precision: <16,6> 
    Strategy: Latency 
