KerasJson: ../example-models/keras/KERAS_3layer_binary_smaller.json
KerasH5:   ../example-models/keras/KERAS_3layer_binary_smaller_weights.h5
OutputDir: quartus_prj/KERAS_3layer_binary_smaller-python3--c5-io_parallel-rf1-_16_6_-Latency
ProjectName: myproject
FPGApart: Arria10
ClockPeriod: 5
Backend: Quartus

IOType: io_parallel
HLSConfig:
  Model:
    ReuseFactor: 1
    Precision: <16,6> 
    Strategy: Latency 
