KerasJson: ../example-models/keras/keras_bnn.json
KerasH5:   ../example-models/keras/keras_bnn_weights.h5
OutputDir: quartus_prj/keras_bnn-python3--c5-io_parallel-rf1-_4_4_-Latency
ProjectName: myproject
FPGApart: Arria10
ClockPeriod: 5
Backend: Quartus

IOType: io_parallel
HLSConfig:
  Model:
    ReuseFactor: 1
    Precision: <4,4> 
    Strategy: Latency 
